// NOTE This file is auto-generated by the Contentlayer CLI

import { Doc, GlobalConfig, Page, DocumentTypes } from './types'

export type * from './types'

export declare const allDocs: Doc[]
export declare const globalConfig: GlobalConfig
export declare const allPages: Page[]

export declare const allDocuments: DocumentTypes[]

