// NOTE This file is auto-generated by the Contentlayer CLI

import { Post, DocumentTypes } from './types'

export type * from './types'

export declare const allPosts: Post[]

export declare const allDocuments: DocumentTypes[]
